// 100 curated quotes — motivation, discipline, stoicism, learning, builder
// energy. Static by design: same quote for everyone on the same day.

export interface Quote {
  text: string;
  author: string | null;
}

export const QUOTES: Quote[] = [
  { text: "You don't rise to your goals. You fall to your systems.", author: "James Clear" },
  { text: "The standard you walk past is the standard you accept.", author: "David Morrison" },
  { text: "Bored people check their phone. Focused people check their progress.", author: null },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "Play long-term games with long-term people.", author: "Naval Ravikant" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "The work you avoid is usually the work that matters.", author: null },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "What you do every day matters more than what you do once in a while.", author: "Gretchen Rubin" },
  { text: "Amateurs sit and wait for inspiration. The rest of us just get up and go to work.", author: "Stephen King" },
  { text: "If it's important, you'll find a way. If it's not, you'll find an excuse.", author: "Ryan Blair" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Move fast and ship. Momentum compounds.", author: null },
  { text: "Your future is hiding in your daily routine.", author: null },
  { text: "Waste no more time arguing what a good person should be. Be one.", author: "Marcus Aurelius" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: null },
  { text: "Knowledge compounds like interest — small deposits, made daily.", author: null },
  { text: "Reading is a conversation with the smartest people who ever lived.", author: null },
  { text: "Repetition is the mother of learning. Spacing is the father of memory.", author: null },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Motivation gets you started. Habit keeps you going.", author: "Jim Ryun" },
  { text: "Slow is smooth. Smooth is fast.", author: null },
  { text: "How you do anything is how you do everything.", author: null },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "Most people overestimate what they can do in a day and underestimate what they can do in a year.", author: null },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: null },
  { text: "The cost of procrastination is the life you could have lived.", author: null },
  { text: "Build in silence. Let results make the noise.", author: null },
  { text: "Specific knowledge is found by pursuing your genuine curiosity.", author: "Naval Ravikant" },
  { text: "Earn with your mind, not your time.", author: "Naval Ravikant" },
  { text: "You can't think your way into a new habit. You act your way into one.", author: null },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
  { text: "Habits are the compound interest of self-improvement.", author: "James Clear" },
  { text: "You do not need more time. You need more focus.", author: null },
  { text: "Deep work is the superpower of the 21st century.", author: "Cal Newport" },
  { text: "Clarity about what matters provides clarity about what does not.", author: "Cal Newport" },
  { text: "If you don't prioritize your life, someone else will.", author: "Greg McKeown" },
  { text: "Starve your distractions. Feed your focus.", author: null },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Success is the product of daily habits — not once-in-a-lifetime transformations.", author: "James Clear" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "What gets measured gets managed.", author: "Peter Drucker" },
  { text: "There is nothing so useless as doing efficiently that which should not be done at all.", author: "Peter Drucker" },
  { text: "Plans are worthless, but planning is everything.", author: "Dwight D. Eisenhower" },
  { text: "Vision without execution is hallucination.", author: "Thomas Edison" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "First say to yourself what you would be; then do what you have to do.", author: "Epictetus" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "While we wait for life, life passes.", author: "Seneca" },
  { text: "He who is everywhere is nowhere.", author: "Seneca" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
  { text: "Long-term consistency beats short-term intensity.", author: "Bruce Lee" },
  { text: "Do the hard thing first. Everything after gets easier.", author: null },
  { text: "Showing up is the whole game. Talent is the tiebreaker.", author: null },
  { text: "Nobody is coming to save you. Good — you won't have to wait.", author: null },
  { text: "Your competition is scrolling. Keep working.", author: null },
  { text: "Future you is watching through your habits.", author: null },
  { text: "Make it work, make it right, make it fast — in that order.", author: "Kent Beck" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The best way out is always through.", author: "Robert Frost" },
  { text: "Action is the antidote to anxiety.", author: null },
  { text: "Direction matters more than speed.", author: null },
  { text: "You can't read the label from inside the jar. Write it down.", author: null },
  { text: "What is not started today is never finished tomorrow.", author: "Goethe" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Goethe" },
  { text: "Inspiration exists, but it has to find you working.", author: "Pablo Picasso" },
  { text: "Only put off until tomorrow what you are willing to die having left undone.", author: "Pablo Picasso" },
  { text: "The scariest moment is always just before you start.", author: "Stephen King" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Pressure is a privilege.", author: "Billie Jean King" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The expert in anything was once a beginner.", author: null },
  { text: "Small daily improvements are the key to staggering long-term results.", author: null },
  { text: "A river cuts through rock not because of its power, but because of its persistence.", author: "James N. Watkins" },
  { text: "Fall seven times, stand up eight.", author: "Japanese proverb" },
  { text: "When you reach the end of your rope, tie a knot and hang on.", author: "Franklin D. Roosevelt" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Focus is about saying no.", author: "Steve Jobs" },
  { text: "Real artists ship.", author: "Steve Jobs" },
];

/** Same quote for everyone on the same calendar day (day-of-year rotation). */
export function getTodaysQuote(): Quote {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) /
      86400000
  );
  return QUOTES[dayOfYear % QUOTES.length];
}
